name: CI

on:
  pull_request:
    branches: [main]

concurrency: ci

jobs:
  run-test:
    name: 'Run Tests'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Public IP
        id: ip
        uses: haythem/public-ip@v1.2

      - name: Docker login
        run: echo ${{ secrets.DOCKER_PAS }} | docker login --username ${{ secrets.DOCKER_USER }} --password-stdin

      - name: Docker start
        run: docker-compose -f ./selenium-grid/docker-compose.yaml up -d
        env:
          HOST_IP: ${{ steps.ip.outputs.ipv4 }}

      - name: Docker wait
        run: ./selenium-grid/wait-for-grid.sh

      - name: Maven test
        run: mvn test

      - name: Docker stop
        run: docker-compose -f ./selenium-grid/docker-compose.yaml down
